config/routes.rb
Rails.application.routes.draw do
  resources :imakokos

end

app/models/imakoko.rb
class Imakoko < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/imakokos_controller.rb
class ImakokosController < ApplicationController
  before_action :set_imakoko, only: [:show, :edit, :update, :destroy]

  # GET /imakokos
  # GET /imakokos.json
  def index
    @imakokos = Imakoko.all
  end

  # GET /imakokos/1
  # GET /imakokos/1.json
  def show
		
		    @hash = Gmaps4rails.build_markers(@imakoko) do |ima, marker|
					marker.lat ima.ido
					marker.lng ima.keido
					marker.infowindow ima.name
					marker.json({title: ima.name})
    end
		
  end

  # GET /imakokos/new
  def new
    @imakoko = Imakoko.new
  end

  # GET /imakokos/1/edit
  def edit
  end

  # POST /imakokos
  # POST /imakokos.json
  def create
    @imakoko = Imakoko.new(imakoko_params)

    respond_to do |format|
      if @imakoko.save
        format.html { redirect_to @imakoko, notice: 'Imakoko was successfully created.' }
        format.json { render :show, status: :created, location: @imakoko }
      else
        format.html { render :new }
        format.json { render json: @imakoko.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imakokos/1
  # PATCH/PUT /imakokos/1.json
  def update
    respond_to do |format|
      if @imakoko.update(imakoko_params)
        format.html { redirect_to @imakoko, notice: 'Imakoko was successfully updated.' }
        format.json { render :show, status: :ok, location: @imakoko }
      else
        format.html { render :edit }
        format.json { render json: @imakoko.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imakokos/1
  # DELETE /imakokos/1.json
  def destroy
    @imakoko.destroy
    respond_to do |format|
      format.html { redirect_to imakokos_url, notice: 'Imakoko was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imakoko
      @imakoko = Imakoko.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imakoko_params
			params.require(:imakoko).permit(:name,:ido,:keido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imakokos_helper.rb
module ImakokosHelper
end

app/views/imakokos/_form.html.erb
<script type="text/javascript">
  if (navigator.geolocation) {

    // 現在の位置情報を取得
    navigator.geolocation.getCurrentPosition(

      // （1）位置情報の取得に成功した場合
      function (pos) {
        var ido = pos.coords.latitude;
        var keido = pos.coords.longitude;

        document.getElementById("imakoko_ido").value = ido;
        document.getElementById("imakoko_keido").value = keido;
        
        },

      // （2）位置情報の取得に失敗した場合
      function (error) {
        var message = "";

        switch (error.code) {

          // 位置情報が取得できない場合
          case error.POSITION_UNAVAILABLE:
            message = "a. 位置情報の取得ができませんでした。";
            break;

          // Geolocationの使用が許可されない場合
          case error.PERMISSION_DENIED:
            message = "b. 位置情報取得の使用許可がされませんでした。";
            break;

          // タイムアウトした場合
          case error.PERMISSION_DENIED_TIMEOUT:
            message = "c. 位置情報取得中にタイムアウトしました。";
            break;
        }
        window.alert(message);
      }
    );
  } else {
    window.alert("d.本ブラウザではGeolocationが使えません");
  }
</script>

<%= form_for(@imakoko) do |f| %>
  <% if @imakoko.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imakoko.errors.count, "error") %> prohibited this imakoko from being saved:</h2>

      <ul>
      <% @imakoko.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<%= f.hidden_field :ido, :value => :ido  %>
<%= f.hidden_field :keido, :value => :keido  %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imakokos/edit.html.erb
<h1>Editing imakoko</h1>

<%= render 'form' %>

<%= link_to 'Show', @imakoko %> |
<%= link_to 'Back', imakokos_path %>

app/views/imakokos/index.html.erb
<h1>Listing imakokos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imakokos.each do |imakoko| %>
      <tr>
        <td><%= imakoko.name %></td>
        <td><%= link_to 'Show', imakoko %></td>
        <td><%= link_to 'Edit', edit_imakoko_path(imakoko) %></td>
        <td><%= link_to 'Destroy', imakoko, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imakoko', new_imakoko_path %>

app/views/imakokos/new.html.erb
<h1>New imakoko</h1>

<%= render 'form' %>

<%= link_to 'Back', imakokos_path %>

app/views/imakokos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @imakoko.name %>
	  <strong>緯度:</strong>
	<%= @imakoko.ido %>
	  <strong>経度:</strong>
	<%= @imakoko.keido %>
	
</p>

<h2>訪問した場所</h2>
    <div id="map" style='width: 100%;height:200px;'></div>


<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {draggable: false,panControl: false,streetViewControl: false}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
	  handler.getMap().setZoom(18);
    });
</script>

<%= link_to 'Edit', edit_imakoko_path(@imakoko) %> |
<%= link_to 'Back', imakokos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kobayan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	
</head>
<body>

<%= yield %>

</body>
</html>